Multiple File Hashing Support
ajalt/python-sha1 pull request #5
Opened 2018-01-23 02:59 UTC by cfahlgren1

Users can now specify more files to be hashed by simply adding command line arguments for the files. Additionally, their is error handling if a file does not exist. I also updated  the README with the new code information.
See image below.

![commandline_image](https://user-images.githubusercontent.com/13546028/35255856-1af7be40-ffbf-11e7-9814-cbbe6848d9d4.png)

2018-01-23 18:06 UTC, ajalt requested changes
I like the idea, there are just a few changes to make.

2018-01-23 18:06 UTC, ajalt commented on README.md
> +A file may also be specified as many arguments to the script:
This is a repeat of the last usage point. Let's remove this section and change the previous existing section from

```
 A file may also be specified as arguments to the script:
 
     $ python sha1.py myfile
     sha1-digest: 3f786850e387550fdab836ed7e6dc881de23001b
```

to 

```
 One or more files may also be specified as arguments to the script:
 
     $ python sha1.py myfile myfile2
     sha1-digest: 3f786850e387550fdab836ed7e6dc881de23001b
     sha1-digest: 57a9901af6fe030198ef1737783e2048ee96da4a
```

2018-01-23 18:06 UTC, ajalt commented on sha1.py
> +from termcolor import colored
I don't want to add any dependencies, let's remove this.

2018-01-23 18:06 UTC, ajalt commented on sha1.py
> +    if len(sys.argv[1:]) == 0:
I want to keep argparse here. You can change the `nargs='?'` to `nargs='*'`. That will allow you to add support for multiple files without changing as much code.

2018-01-24 01:27 UTC, cfahlgren1 reviewed
I have implemented the review issues and have implemented the code according to the existing argsparse code.

2018-01-24 17:06 UTC, ajalt requested changes
Almost there! Just a couple more changes.

2018-01-24 17:06 UTC, ajalt commented on sha1.py
> +                data = argument
Hashing a literal string in an argument list is not very intuitive or useful; let's just remove it and only support file paths.

2018-01-24 17:06 UTC, ajalt commented on sha1.py
> +                print('Error, ' + argument + " file not found")
This error is a bit misleading: the data has already been read into memory at this point, so exceptions won't be because the file doesn't exist. Given that the `sha1` doesn't raise exceptions, I say we don't need a `try`/`except` here at all.

2018-01-24 17:51 UTC, cfahlgren1 reviewed
Yes, I saw the unneeded code and fixed the AttributeError issue.

2018-01-24 17:58 UTC, ajalt approved these changes
Looks good, thanks!

2018-01-24 17:58 UTC, merged

2018-01-24 18:02 UTC, cfahlgren1 commented
Appreciate it. Learned alot from my first PR